// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	todo.proto

It has these top-level messages:
	TodoRequest
	TodoResponse
	TodosRequest
	TodosResponse
	Todo
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TodoRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *TodoRequest) Reset()                    { *m = TodoRequest{} }
func (m *TodoRequest) String() string            { return proto.CompactTextString(m) }
func (*TodoRequest) ProtoMessage()               {}
func (*TodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TodoResponse struct {
	Todo *Todo `protobuf:"bytes,1,opt,name=todo" json:"todo,omitempty"`
}

func (m *TodoResponse) Reset()                    { *m = TodoResponse{} }
func (m *TodoResponse) String() string            { return proto.CompactTextString(m) }
func (*TodoResponse) ProtoMessage()               {}
func (*TodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type TodosRequest struct {
}

func (m *TodosRequest) Reset()                    { *m = TodosRequest{} }
func (m *TodosRequest) String() string            { return proto.CompactTextString(m) }
func (*TodosRequest) ProtoMessage()               {}
func (*TodosRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type TodosResponse struct {
	Todos []*Todo `protobuf:"bytes,1,rep,name=todos" json:"todos,omitempty"`
}

func (m *TodosResponse) Reset()                    { *m = TodosResponse{} }
func (m *TodosResponse) String() string            { return proto.CompactTextString(m) }
func (*TodosResponse) ProtoMessage()               {}
func (*TodosResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TodosResponse) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

type Todo struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Completed bool   `protobuf:"varint,2,opt,name=completed" json:"completed,omitempty"`
	Title     string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Message   string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
}

func (m *Todo) Reset()                    { *m = Todo{} }
func (m *Todo) String() string            { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()               {}
func (*Todo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*TodoRequest)(nil), "pb.TodoRequest")
	proto.RegisterType((*TodoResponse)(nil), "pb.TodoResponse")
	proto.RegisterType((*TodosRequest)(nil), "pb.TodosRequest")
	proto.RegisterType((*TodosResponse)(nil), "pb.TodosResponse")
	proto.RegisterType((*Todo)(nil), "pb.Todo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TodoService service

type TodoServiceClient interface {
	GetTodos(ctx context.Context, in *TodosRequest, opts ...grpc.CallOption) (*TodosResponse, error)
	GetTodo(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error)
	UpdateTodo(ctx context.Context, in *Todo, opts ...grpc.CallOption) (*TodoResponse, error)
	DeleteTodo(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) GetTodos(ctx context.Context, in *TodosRequest, opts ...grpc.CallOption) (*TodosResponse, error) {
	out := new(TodosResponse)
	err := grpc.Invoke(ctx, "/pb.TodoService/GetTodos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) GetTodo(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := grpc.Invoke(ctx, "/pb.TodoService/GetTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) UpdateTodo(ctx context.Context, in *Todo, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := grpc.Invoke(ctx, "/pb.TodoService/UpdateTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) DeleteTodo(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := grpc.Invoke(ctx, "/pb.TodoService/DeleteTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TodoService service

type TodoServiceServer interface {
	GetTodos(context.Context, *TodosRequest) (*TodosResponse, error)
	GetTodo(context.Context, *TodoRequest) (*TodoResponse, error)
	UpdateTodo(context.Context, *Todo) (*TodoResponse, error)
	DeleteTodo(context.Context, *TodoRequest) (*TodoResponse, error)
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_GetTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).GetTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TodoService/GetTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).GetTodos(ctx, req.(*TodosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_GetTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).GetTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TodoService/GetTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).GetTodo(ctx, req.(*TodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_UpdateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Todo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).UpdateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TodoService/UpdateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).UpdateTodo(ctx, req.(*Todo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_DeleteTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).DeleteTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TodoService/DeleteTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).DeleteTodo(ctx, req.(*TodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodos",
			Handler:    _TodoService_GetTodos_Handler,
		},
		{
			MethodName: "GetTodo",
			Handler:    _TodoService_GetTodo_Handler,
		},
		{
			MethodName: "UpdateTodo",
			Handler:    _TodoService_UpdateTodo_Handler,
		},
		{
			MethodName: "DeleteTodo",
			Handler:    _TodoService_DeleteTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4e, 0xf3, 0x30,
	0x14, 0x84, 0xff, 0xa4, 0xe9, 0xdf, 0x74, 0x0a, 0xa5, 0x3c, 0xb1, 0xb0, 0x50, 0x41, 0x91, 0x57,
	0x15, 0x42, 0x41, 0x2d, 0x57, 0x40, 0x62, 0x1f, 0xe0, 0x00, 0x4d, 0xfd, 0x84, 0x22, 0xb5, 0xd8,
	0xd4, 0x86, 0x6b, 0x72, 0x25, 0x14, 0xdb, 0x49, 0x01, 0xb1, 0x60, 0x39, 0xe3, 0x99, 0xa7, 0xf9,
	0x64, 0xc0, 0x69, 0xa5, 0x4b, 0xb3, 0xd7, 0x4e, 0x53, 0x6a, 0x6a, 0x79, 0x81, 0xc9, 0xa3, 0x56,
	0xba, 0xe2, 0xd7, 0x37, 0xb6, 0x8e, 0xa6, 0x48, 0x1b, 0x25, 0x92, 0x22, 0x59, 0x8c, 0xab, 0xb4,
	0x51, 0xf2, 0x1a, 0x47, 0xe1, 0xd9, 0x1a, 0xfd, 0x62, 0x99, 0xe6, 0xc8, 0xda, 0x03, 0x3e, 0x31,
	0x59, 0xe5, 0xa5, 0xa9, 0x4b, 0xff, 0xee, 0x5d, 0x39, 0x0d, 0x69, 0x1b, 0xaf, 0xc9, 0x1b, 0x1c,
	0x47, 0x1d, 0xeb, 0x97, 0x18, 0xb6, 0x41, 0x2b, 0x92, 0x62, 0xf0, 0xad, 0x1f, 0x6c, 0xa9, 0x90,
	0xb5, 0xf2, 0xe7, 0x0c, 0x9a, 0x63, 0xbc, 0xd1, 0x3b, 0xb3, 0x65, 0xc7, 0x4a, 0xa4, 0x45, 0xb2,
	0xc8, 0xab, 0x83, 0x41, 0x67, 0x18, 0xba, 0xc6, 0x6d, 0x59, 0x0c, 0x7c, 0x21, 0x08, 0x12, 0x18,
	0xed, 0xd8, 0xda, 0xf5, 0x33, 0x8b, 0xcc, 0xfb, 0x9d, 0x5c, 0x7d, 0x24, 0x01, 0xfa, 0x81, 0xf7,
	0xef, 0xcd, 0x86, 0x69, 0x89, 0xfc, 0x9e, 0x9d, 0x5f, 0x4a, 0xb3, 0x6e, 0x52, 0x07, 0x71, 0x7e,
	0xfa, 0xc5, 0x09, 0x18, 0xf2, 0x1f, 0x95, 0x18, 0xc5, 0x0a, 0x9d, 0xf4, 0x10, 0xb1, 0x30, 0x3b,
	0x18, 0x7d, 0xfe, 0x0a, 0x78, 0x32, 0x6a, 0xed, 0xd8, 0x57, 0x7a, 0xee, 0x5f, 0xb3, 0x4b, 0xe0,
	0x8e, 0x5b, 0xb2, 0x3f, 0x9f, 0xaf, 0xff, 0xfb, 0x0f, 0xbd, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff,
	0x1b, 0x48, 0xc2, 0x18, 0xde, 0x01, 0x00, 0x00,
}
